import type { Metadata } from "next";

import '@/styles/globals.css'

import {Edu_AU_VIC_WA_NT_Hand} from "next/font/google"
import {Header} from "@/components/Header"

const roboto=Edu_AU_VIC_WA_NT_Hand({
  subsets:["latin"],
  weight:["400","700"]  
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
